---
- name: 'install Dnsmasq'
  apt:
    name: dnsmasq
    state: '{{dnsmasq_state}}'
    update_cache: false
  notify: handler_dnsmasq
  become: true
  tags: ct-dnsmasq

- name: 'transfer script to brute force systemd resolver service'
  copy:
    src: control_systemd_resolverd.sh
    dest: /usr/local/bin/control_systemd_resolverd.sh
    group: root
    mode: '0755'
    owner: root
  become: true
  tags:
  - ct-dnsmasq

- name: 'stop and disable Systemd resolver service'
  systemd:
    name: systemd-resolved.service
    enabled: false
    state: stopped
  notify:
  - handler_dnsmasq
  - handler_force_death_resolverd  # workaround
  become: true
  tags:
  - ct-dnsmasq
  - ct-dnsmasq-svc

- name: 'mask systemd resolver service'
  systemd:
    name: systemd-resolved.service
    masked: true
  notify:
  - handler_force_death_resolverd  # workaround
  become: true
  tags:
  - ct-dnsmasq
  - ct-dnsmasq-svc

- name: 'get status of {{dnsmasq_resolv_conf}} (CM:false)'
  stat:
    path: '{{dnsmasq_resolv_conf}}'
  check_mode: false
  register: stat_resolver
  tags: ct-dnsmasq

- name: 'remove {{dnsmasq_resolv_conf}} if it is a symlink'
  file:
    path: '{{dnsmasq_resolv_conf}}'
    state: absent
  when:
  - stat_resolver.stat.islnk is defined
  - stat_resolver.stat.islnk
  become: true
  tags: ct-dnsmasq

- name: 'render Dnsmasq config file'
  template:
    src: default.j2
    dest: '{{dnsmasq_etc_dir}}/default'
    group: root
    mode: '0644'
    owner: root
  become: true
  tags: ct-dnsmasq

- name: 'render {{dnsmasq_resolv_conf}}'
  template:
    src: default.j2
    dest: '{{dnsmasq_etc_dir}}/default'
    group: root
    mode: '0644'
    owner: root
  become: true
  tags: ct-dnsmasq

- name: 'render details of fallback nameserver'
  template:
    src: forwarding_nameserver.j2
    dest: /var/run/dnsmasq/resolv.conf
    group: root
    mode: '0644'
    owner: root
  become: true
  tags: ct-dnsmasq

- name: 'start Dnsmasq service'
  systemd:
    name: systemd-resolved.service
    enabled: true
    masked: false
    state: started
  notify: handler_dnsmasq
  become: true
  tags:
  - ct-dnsmasq
  - ct-dnsmasq-svc
...
