---
- name: 'handler_restart_dnsmasq'
  systemd:
    name: '{{dnsmasq_unit_name}}'
    daemon_reload: true
    state: restarted
  become: true

- name: 'handler_reboot_server'
  reboot:
  when: dnsmasq_ok_to_reboot
  become: true
...
